version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gofinance
      - POSTGRES_PASSWORD=docker
  myapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/gofinance
volumes:
  db:
    driver: local
