version: '3.7'

services:
  db:
    image: postgres
    container_name: database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=gofinance
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:
    driver: local
